# Generated by Django 6.0.1 on 2026-01-26 21:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(choices=[('FICTION', 'Художественная литература'), ('SCIFI', 'Научная фантастика'), ('FANTASY', 'Фэнтези'), ('CLASSIC', 'Классика'), ('DETECTIVE', 'Детектив'), ('ROMANCE', 'Роман'), ('HISTORY', 'Историческая'), ('PSYCHOLOGY', 'Психология'), ('PHILOSOPHY', 'Философия'), ('CHILDREN', 'Детская'), ('OTHER', 'Другое')], default='FICTION', max_length=50, verbose_name='Жанр')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('reading_reason', models.TextField(blank=True, verbose_name='Почему стоит прочитать')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена (₽)')),
                ('isbn', models.CharField(blank=True, help_text='Международный стандартный книжный номер', max_length=13, null=True, verbose_name='ISBN')),
                ('publication_year', models.PositiveIntegerField(blank=True, help_text='Год первой публикации', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Год издания')),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Объем книги в страницах', null=True, verbose_name='Количество страниц')),
                ('cover_image', models.ImageField(blank=True, help_text='Изображение обложки', null=True, upload_to='books/covers/', verbose_name='Обложка книги')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
