# Generated by Django 6.0.1 on 2026-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз просмотрена страница книги', verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Изображение обложки', null=True, upload_to='book/covers/', verbose_name='Обложка книги'),
        ),
    ]
