# Generated by Django 6.0.1 on 2026-01-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookreview_views_count_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='views_count',
        ),
    ]
